#!/usr/bin/env python3
"""Generate a synthetic EH-funclet calibration corpus (real C++, no assembly).

The reference DLL's unwind funclets are self-contained code such as
``lea ecx,[ebp-off]; jmp ~T`` that depend only on the parent's frame layout,
not on the parent's identity. Probe functions with destructable locals at
chosen stack offsets emit the same funclets; chained locals step the offset
deterministically so a sweep covers every disp8 operand the reference uses.
"""
import argparse,csv,json
from pathlib import Path

HEADER = """// Generated by tools/make_eh_probe_corpus.py -- real C++ funclet probes.
struct ProbeDtor { ProbeDtor(); ~ProbeDtor(); };
struct ProbeD4 { int v; ProbeD4(); ~ProbeD4(); };
struct ProbePOD { int v; };
struct ProbeSub { ~ProbeSub(); };
struct ProbeThrow { ProbeThrow(); ~ProbeThrow(); };
struct ProbeThrow4 { int v; ProbeThrow4(); ~ProbeThrow4(); };
extern void probe_throw();
extern void probe_sink(void *);
extern int probe_cond();
extern ProbeSub *probe_psub();
extern ProbeDtor probe_make();
extern ProbeD4 probe_make4();
extern void probe_sink2(ProbeDtor, ProbeDtor);
extern void probe_sink24(ProbeD4, ProbeD4);
extern void probe_sinkm(ProbeDtor, ProbeD4, ProbeDtor);
extern ProbeDtor *probe_pdt();
extern ProbeD4 *probe_pd4();
extern void *operator new(unsigned int);
extern void operator delete(void *, unsigned int);
"""


def emit_lea_chains(out, count):
    # Nested scopes: each local gets its own unwind state -> one 8-byte
    # funclet each (lea ecx,[ebp-off_i]; jmp ~ProbeD4), offsets stepping by
    # sizeof(ProbeD4)=4 across the chain. MSVC caps nesting ~120 blocks.
    count = min(count, 100)
    for k in range(1, count + 1):
        body = ''
        for i in range(k):
            body += f'{{ ProbeD4 t{i}; '
        body += 'probe_throw();' + ' }' * k
        out.append(f"void probe_lea_{k:04d}() {{ {body} }}")
    # Wider steps for deeper disp32 offsets.
    for sz in (8, 16, 32):
        out.append(
            f"struct ProbeD{sz} {{ long long v[{sz // 8}]; ~ProbeD{sz}(); }};")
        for k in range(1, count + 1):
            body = ''
            for i in range(k):
                body += f'{{ ProbeD{sz} t{i}; '
            body += 'probe_throw();' + ' }' * k
            out.append(f"void probe_d{sz}_{k:04d}() {{ {body} }}")


def emit_mov_chains(out, count):
    # Copy-initialised temporaries in nested scopes -> hidden pointer slots ->
    #   mov ecx,[ebp-off_i]; jmp ~ProbeD4
    count = min(count, 100)
    for k in range(1, count + 1):
        body = ''
        for i in range(k):
            body += f'{{ ProbeD4 t{i} = probe_make4(); '
        body += 'probe_throw();' + ' }' * k
        out.append(f"void probe_mov_{k:04d}() {{ {body} }}")


def emit_delete_chains(out, count):
    # Sized-delete cleanup of a new-expression pointer ->
    #   push sz; mov eax,[ebp-p]; push eax; call delete; add esp,8; ret
    # Sizes sweep both the imm8 (push sz) and imm32 (push imm32) forms and
    # the pointer slot walks with the pad index.
    for k in range(count):
        pad = f'int pad[{k}]; ' if k else ''
        out.append(
            f"void probe_del_{k:04d}() {{ {pad}"
            f"ProbeD4 *p = new ProbeD4; probe_throw(); }}"
        )
    for sz in range(4, 260, 4):
        out.append(
            f"struct ProbeDel{sz:03d} {{ char c[{sz}]; ~ProbeDel{sz:03d}(); }};\n"
            f"void probe_del_sz{sz:03d}() {{ ProbeDel{sz:03d} *p = "
            f"new ProbeDel{sz:03d}; probe_throw(); }}"
        )


def emit_member_sweep(out, count):
    # Member cleanup in a ctor unwinds via this=[ebp+8]:
    #   member at offset 0 -> mov ecx,[ebp+8]; jmp ~Sub        (8 bytes)
    #   member at offset N -> mov ecx,[ebp+8]; add ecx,N; jmp  (11 bytes)
    for k in range(count):
        pad = f'int pad[{k}]; ' if k else ''
        out.append(
            f"struct ProbeHost{k:04d} {{ {pad}ProbeSub m; "
            f"ProbeHost{k:04d}(); }};\n"
            f"ProbeHost{k:04d}::ProbeHost{k:04d}() {{ probe_throw(); }}"
        )


def emit_flag_members(out, members):
    # Function-try-block ctors track constructed members with flag bits ->
    #   mov eax,[ebp-flag]; and eax,<bit>; jz; and flag,~bit;
    #   lea ecx,[ebp-m]; jmp ~Sub; ret                        (25 bytes)
    # Member size shifts the flag dword and member offsets; count shifts the
    # tested bit, so sweep both.
    for sz in (4, 8, 16, 32):
        for n in range(2, members + 1):
            decls = ' '.join(f'ProbeSub m{i};' for i in range(n)) \
                if sz == 4 else \
                ' '.join(f'ProbeD{sz} m{i};' for i in range(n))
            out.append(
                f"struct ProbeFlag{sz:02d}n{n:02d} {{ {decls} "
                f"ProbeFlag{sz:02d}n{n:02d}(); }};\n"
                f"ProbeFlag{sz:02d}n{n:02d}::ProbeFlag{sz:02d}n{n:02d}() "
                f"try {{ probe_throw(); }} catch (...) {{ throw; }}"
            )


def emit_throwing_flags(out, members):
    # Members whose ctors may throw force MSVC to track construction state
    # in a flag dword; unwind funclets then emit
    #   mov eax,[ebp-flag]; and eax,<bit>; jz; and flag,~bit;
    #   lea ecx,[ebp-m]; jmp ~Throw
    # Plain (non-function-try) ctors emit unwind funclets for partial
    # construction; function-try ctors add the catch-rethrow form.
    for n in range(2, members + 1):
        decls = ' '.join(f'ProbeThrow m{i};' for i in range(n))
        tag = f'n{n:02d}'
        out.append(
            f"struct ProbeTF{tag} {{ {decls} ProbeTF{tag}(); }};\n"
            f"ProbeTF{tag}::ProbeTF{tag}() {{ probe_throw(); }}"
        )
        out.append(
            f"struct ProbeTG{tag} {{ {decls} ProbeTG{tag}(); }};\n"
            f"ProbeTG{tag}::ProbeTG{tag}() try {{ probe_throw(); }} "
            f"catch (...) {{ throw; }}"
        )
        out.append(
            f"struct ProbeTH{tag} {{ {decls} ProbeTH{tag}(); }};\n"
            f"ProbeTH{tag}::ProbeTH{tag}() try : m0() {{ probe_throw(); }} "
            f"catch (...) {{ throw; }}"
        )
    # Same with sized members (member offset 4) and mixed tails so the flag
    # dword lands at different frame slots.
    for n in range(2, members + 1):
        decls = ' '.join(f'ProbeThrow4 m{i};' for i in range(n))
        tag = f'w{n:02d}'
        out.append(
            f"struct ProbeTF{tag} {{ {decls} ProbeTF{tag}(); }};\n"
            f"ProbeTF{tag}::ProbeTF{tag}() {{ probe_throw(); }}"
        )
        out.append(
            f"struct ProbeTG{tag} {{ {decls} ProbeTG{tag}(); }};\n"
            f"ProbeTG{tag}::ProbeTG{tag}() try {{ probe_throw(); }} "
            f"catch (...) {{ throw; }}"
        )
    # One throwing member after K sub members / before them, in a function
    # whose frame also carries nested locals.
    for k in range(0, members + 1):
        subs = ' '.join(f'ProbeSub s{i};' for i in range(k))
        out.append(
            f"struct ProbeTM{k:02d} {{ {subs} ProbeThrow m; "
            f"ProbeTM{k:02d}(); }};\n"
            f"ProbeTM{k:02d}::ProbeTM{k:02d}() {{ probe_throw(); }}"
        )
        out.append(
            f"struct ProbeTN{k:02d} {{ ProbeThrow m; {subs} "
            f"ProbeTN{k:02d}(); }};\n"
            f"ProbeTN{k:02d}::ProbeTN{k:02d}() {{ probe_throw(); }}"
        )


def emit_array_members(out, count):
    # Array members inside ctor/dtor probes ->
    #   lea eax,[ecx+N]; push eax; call vector-dtor            (13+ bytes)
    # An int member in front shifts the array to field offset 4.
    for pre in ('', 'int p; '):
        for k in range(1, count + 1):
            tag = f'p{k:04d}' if pre else f'{k:04d}'
            out.append(
                f"struct ProbeArrH{tag} {{ {pre}ProbeSub m[{k}]; "
                f"ProbeArrH{tag}(); }};\n"
                f"ProbeArrH{tag}::ProbeArrH{tag}() {{ probe_throw(); }}"
            )


def emit_member_new_probes(out, count):
    # new-expression pointer cleanup destroying a member through the stored
    # pointer ->  mov ecx,[ebp-p]; add ecx,N; jmp ~Sub          (11 bytes)
    for k in range(count):
        pad = f'int pad[{k}]; ' if k else ''
        out.append(
            f"struct ProbePtr{k:04d} {{ {pad}ProbeSub m; }};\n"
            f"void probe_pnew_{k:04d}() {{ ProbePtr{k:04d} *p = "
            f"new ProbePtr{k:04d}; probe_throw(); }}"
        )


def emit_array_sweep(out, count):
    # Array dtor -> flag/vector cleanup funclets.
    for k in range(count):
        out.append(
            f"void probe_arr_{k:04d}() {{ int pad[{k + 1}]; probe_sink(&pad[0]); "
            f"ProbeDtor a[4]; probe_throw(); }}"
        )


def needed_operands(reference, image, layout, inventory):
    """Extract the exact operand sets the reference still needs.

    Every uncovered funclet shape decodes to (family, immediate); emitting a
    probe for each distinct immediate is far tighter than blind sweeps.
    """
    import re as _re
    base = layout['image_base']
    text = next(s for s in layout['sections'] if s['name'] == '.text')
    o, rs, rva0 = text['raw_offset'], text['raw_size'], text['rva']
    sets = {
        'add_off': set(),   # member offset N in add ecx,N
        'deep_lea': set(),  # disp32 magnitude for lea ecx,[ebp-V]
        'del_sz': set(),    # sized-delete imm
        'flag_mask': set(), # and eax,imm flag masks
        'flag_clr': set(),  # (slot, mask) for and dword[ebp-slot],mask
    }
    ext_mask = bytearray(rs)
    for row in csv.DictReader(open(inventory), delimiter='\t'):
        va = int(row['entry'], 16)
        size = int(row['body_bytes'])
        if not size:
            continue
        rva = va - base
        if not (rva0 <= rva < rva0 + rs):
            continue
        for i in range(rva - rva0, min(rs, rva - rva0 + size)):
            ext_mask[i] = 1
        if size > 64:
            continue
        off = o + rva - rva0
        exp = reference[off:off + size]
        if image[off:off + size] == exp:
            continue
        m = _re.match(rb'\x8b\x4d.\x83\xc1(.)', exp)
        if m:
            sets['add_off'].add(m.group(1)[0])
            continue
        m = _re.match(rb'\x8b\x4d.\x81\xc1(....)', exp)
        if m:
            sets['add_off'].add(int.from_bytes(m.group(1), 'little'))
            continue
        m = _re.match(rb'\x8d\x8d(....)\xe9', exp)
        if m:
            v = int.from_bytes(m.group(1), 'little')
            sets['deep_lea'].add(v - 0x100000000 if v >= 0x80000000 else v)
            continue
        m = _re.match(rb'\x68(....)\x8b.', exp)
        if m:
            v = int.from_bytes(m.group(1), 'little')
            if v < 0x10000:
                sets['del_sz'].add(v)
            continue
        m = _re.match(rb'\x8b\x45.\x83\xe0(.)', exp)
        if m:
            sets['flag_mask'].add(m.group(1)[0])
            continue
        m = _re.match(rb'\x8b\x45.\x25(....)', exp)
        if m:
            sets['flag_mask'].add(int.from_bytes(m.group(1), 'little'))
            continue
    # Scan fully-differing runs OUTSIDE the inventory for the same families.
    diff = bytes(a != b for a, b in
                 zip(reference[o:o + rs], image[o:o + rs]))
    i = 0
    while i < rs:
        if not (diff[i] and not ext_mask[i]):
            i += 1
            continue
        j = i
        while j < rs and diff[j] and not ext_mask[j]:
            j += 1
        exp = reference[o + i:o + j]
        m = _re.match(rb'\x8b\x45(.)\x83\xe0(.)', exp)
        if m:
            sets['flag_mask'].add(m.group(2)[0])
            i = j
            continue
        m = _re.match(rb'\x8b\x45(.)\x25(....)', exp)
        if m:
            sets['flag_mask'].add(int.from_bytes(m.group(2), 'little'))
            i = j
            continue
        m = _re.match(rb'\x83\x65(.)(.)', exp)
        if m:
            sets['flag_clr'].add((m.group(1)[0], m.group(2)[0]))
            i = j
            continue
        m = _re.match(rb'\x6a(.)\x8b\x45', exp)
        if m:
            sets['del_sz'].add(m.group(1)[0])
            i = j
            continue
        m = _re.match(rb'\x68(....)\x8b.', exp)
        if m:
            v = int.from_bytes(m.group(1), 'little')
            if v < 0x10000:
                sets['del_sz'].add(v)
            i = j
            continue
        i = j
    return sets


def _nest(inner, depth, decl='ProbeD4'):
    """Wrap ``inner`` in ``depth`` nested scopes holding one local each so the
    statement's temporaries land at stepped frame offsets."""
    body = inner
    for i in range(depth):
        body = f'{{ {decl} n{i}; {body} }}'
    return body


def emit_targeted(out, sets):
    # Member offset N: struct with member at exactly N; new-expression cleanup
    # walks the stored pointer + N. The pointer slot's [ebp-disp] depends on
    # frame layout, so nest the expression at several chain depths to sweep
    # the disp8 neighbourhood of every reference slot operand.
    for n in sorted(sets['add_off']):
        if n <= 0 or n > 0x8000:
            continue
        pad = f'char pad[{n - 1}]; ' if n > 1 else ''
        out.append(
            f'struct ProbeOff{n:05x} {{ {pad}ProbeSub m; }};'
        )
        for d in range(0, 17):
            out.append(
                f'void probe_off_{n:05x}_{d}() {{ '
                + _nest(f'ProbeOff{n:05x} *p = new ProbeOff{n:05x}; '
                        'probe_throw();', d)
                + ' }'
            )
    # Deep locals: reference disps sit a few bytes off the object's size
    # because the parent's frame carries extra EH temps. Emit a small size
    # neighbourhood around each needed magnitude so one variant lands on the
    # exact disp.
    for v in sorted(sets['deep_lea']):
        size = -v
        if size < 8 or size > 0x40000:
            continue
        for delta in (-12, -8, -4, 0, 4, 8, 12):
            s = size + delta
            if s < 8:
                continue
            out.append(
                f'struct ProbeDeep{v & 0xffffffff:08x}_{delta & 0x1f:02x} {{ '
                f'char c[{s - 4}]; ProbeD4 m; '
                f'~ProbeDeep{v & 0xffffffff:08x}_{delta & 0x1f:02x}(); }};\n'
                f'void probe_deep_{v & 0xffffffff:08x}_{delta & 0x1f:02x}() {{ '
                f'ProbeDeep{v & 0xffffffff:08x}_{delta & 0x1f:02x} x; '
                f'probe_throw(); }}'
            )
    # Sized deletes: new char[sz] cleanup is
    #   push sz; mov eax,[ebp-p]; push eax; call delete(p,sz)...
    # Nest each size so the pointer slot sweeps the needed disp range.
    # Two layouts: pointer deepest (nest wraps it) and pointer first
    # (shallow slot, pad locals deeper).
    for sz in sorted(sets['del_sz']):
        if sz < 4 or sz > 0x8000:
            continue
        for d in range(0, 17):
            out.append(
                f'void probe_dsz_{sz:05x}_{d}() {{ '
                + _nest(f'char *p = new char[{sz}]; probe_throw();', d)
                + ' }'
            )
            out.append(
                f'void probe_dszf_{sz:05x}_{d}() {{ '
                f'char *p = new char[{sz}]; '
                + _nest('probe_throw();', d)
                + ' }'
            )
        if 8 <= sz <= 0x400:
            out.append(
                f'struct ProbeA{sz:05x} {{ char c[{sz}]; '
                f'~ProbeA{sz:05x}(); }};\n'
                f'void probe_dva_{sz:05x}() {{ ProbeA{sz:05x} *p = '
                f'new ProbeA{sz:05x}[2]; probe_throw(); }}'
            )
    # Flag-clears: a catch block that returns to try-level resets the
    # construction-flag dword ->  and dword[ebp-slot],mask
    seen_masks = set()
    for slot, mask in sorted(sets.get('flag_clr', ())):
        # slot is a signed disp8; negative slots (ebp-0x10 -> 0xf0) are the
        # common case, so only dedupe on the mask -- the nest sweep covers
        # the slot neighbourhood either way.
        if not mask or mask in seen_masks:
            continue
        seen_masks.add(mask)
        bit = (~mask & 0xff).bit_length()
        decls = ' '.join(f'ProbeSub m{i};' for i in range(min(bit, 24)))
        for d in range(0, 9):
            tag = f'{slot:02x}_{mask:02x}_{d}'
            out.append(
                f'void probe_fclr_{tag}() {{ '
                + _nest('try { probe_throw(); } catch (...) '
                        '{ probe_sink(0); }', d)
                + ' }'
            )
            sinks = '; '.join(['probe_sink(0)'] * (d + 1))
            out.append(
                f'struct ProbeFC{tag} {{ {decls} ProbeFC{tag}(); }};\n'
                f'ProbeFC{tag}::ProbeFC{tag}() try '
                f'{{ probe_throw(); {sinks}; }} catch (...) {{ throw; }}'
            )
    # Flag masks: function-try ctor with enough members to reach bit N.
    # The flag dword's frame slot depends on the parent's local layout,
    # so sweep ctor-body padding to shift it through the observed disp8
    # neighbourhood, and emit sequential + nested conditional locals for
    # frames that track object lifetimes with flag bits instead.
    for mask in sorted(sets['flag_mask']):
        if mask <= 0 or (mask & (mask - 1)):
            continue  # only power-of-2 bits are member-init flags
        bit = mask.bit_length() - 1
        decls = ' '.join(f'ProbeSub m{i};' for i in range(bit + 1))
        out.append(
            f'struct ProbeFM{mask:08x} {{ {decls} ProbeFM{mask:08x}(); }};\n'
            f'ProbeFM{mask:08x}::ProbeFM{mask:08x}() try {{ probe_throw(); }}'
            f' catch (...) {{ throw; }}'
        )
        for pad in range(1, 13):
            tag = f'{mask:08x}_{pad}'
            out.append(
                f'struct ProbeFP{tag} {{ {decls} ProbeFP{tag}(); }};\n'
                f'ProbeFP{tag}::ProbeFP{tag}() try '
                f'{{ int pad[{pad}]; probe_sink(&pad[0]); probe_throw(); }}'
                f' catch (...) {{ throw; }}'
            )
        # Nested conditional locals: overlapping lifetimes give each
        # object its own flag bit.
        inner = 'probe_throw();'
        for i in range(bit + 1):
            inner = (f'if (probe_cond()) {{ ProbeSub t{i}; '
                     f'probe_sink(&t{i}); {inner} }}')
        for pad in range(0, 9):
            pl = f'int q[{pad}]; probe_sink(&q[0]); ' if pad else ''
            out.append(
                f'void probe_fq_{mask:08x}_{pad}() {{ {pl}{inner} }}'
            )
        # Sequential conditional locals: MSVC may assign distinct bits
        # even when lifetimes are disjoint.
        seq = ' '.join(
            f'if (probe_cond()) {{ ProbeSub s{i}; probe_sink(&s{i}); }}'
            for i in range(bit + 1))
        for pad in range(0, 9):
            pl = f'int r[{pad}]; probe_sink(&r[0]); ' if pad else ''
            out.append(
                f'void probe_fs_{mask:08x}_{pad}() {{ {pl}{seq} '
                f'probe_throw(); }}'
            )


def emit_extra_families(out, count):
    # Catch-by-value/ref handlers make the framehandler pass the thrown object
    # through a second stack arg -> funclets reading [esp+8].
    forms = (
        'catch (ProbeSub o) { probe_sink(&o); }',
        'catch (ProbeSub &o) { probe_sink(&o); }',
        'catch (ProbeSub o) { o.~ProbeSub(); }',
        'catch (int o) { probe_sink(&o); }',
    )
    for i, form in enumerate(forms):
        for d in range(0, count):
            out.append(
                f'void probe_cref_{i}_{d}() {{ '
                + _nest(f'try {{ probe_throw(); }} {form}', d)
                + ' }'
            )
    # Indirect-call stubs: a call through a global function pointer emits
    #   ff15 <&fp> ; cc/c3 -> IAT-thunk shape.
    for k in range(8):
        out.append(
            f'extern void (*volatile probe_fp{k})();\n'
            f'void probe_iat_{k}() {{ probe_fp{k}(); }}'
        )
        out.append(
            f'extern void (*volatile probe_fq{k})();\n'
            f'void probe_iatq_{k}() {{ probe_fq{k}(); __assume(0); }}'
        )
    # Conditional construction: MSVC tracks a conditionally-built local with
    # flag bits ->  mov eax,[ebp-flag]; and eax,bit; jz; and [flag],~bit;
    #               (lea|mov) ecx,obj; jmp ~T; ret
    for d in range(count):
        out.append(
            f'void probe_cond_{d}() {{ '
            + _nest('if (probe_cond()) { ProbeSub t; probe_throw(); }',
                    d)
            + ' }'
        )
        out.append(
            f'void probe_condp_{d}() {{ ProbeSub *p = probe_psub(); '
            + _nest('if (probe_cond()) delete p; probe_throw();', d)
            + ' }'
        )
        out.append(
            f'void probe_condm_{d}() {{ '
            + _nest('if (probe_cond()) { ProbeDtor t; } probe_throw();',
                    d)
            + ' }'
        )
    # Member-init new-expressions in function-try ctors use construction-flag
    # bits ->  mov eax,[ebp-flag]; and eax,bit; jz; and [flag],~bit;
    #          mov ecx,[ebp-this]; jmp ~T; ret
    for d in range(count):
        for n in (1, 2, 4):
            pad = f'int pad[{d}]; ' if d else ''
            mems = ' '.join(f'ProbeSub *p{i};' for i in range(n))
            init = ', '.join(f'p{i}(new ProbeSub)' for i in range(n))
            tag = f'{d}_{n}'
            out.append(
                f'struct ProbeNI{tag} {{ {pad}{mems} ProbeNI{tag}(); }};\n'
                f'ProbeNI{tag}::ProbeNI{tag}() try : {init} '
                f'{{ probe_throw(); }} catch (...) {{ throw; }}'
            )
            out.append(
                f'struct ProbeNJ{tag} {{ {pad}{mems} ProbeNJ{tag}(); }};\n'
                f'ProbeNJ{tag}::ProbeNJ{tag}() : {init} '
                f'{{ probe_throw(); }}'
            )
    # Broad hunt for MSVC's flag-bit construction tracking: the reference
    # emits  mov eax,[ebp-flag]; and eax,bit; jz; and [flag],~bit; cleanup
    # for objects whose construction the state machine cannot express.
    # Try every construct known to force runtime "was it built" tracking.
    variants = (
        # object in if-init / switch-init (C++17) and while-condition
        'if (ProbeSub t = *probe_psub(); probe_cond()) { probe_throw(); }',
        'switch (ProbeSub t = *probe_psub(); probe_cond()) '
        '{ case 0: probe_throw(); }',
        'while (probe_cond()) { ProbeSub t; probe_throw(); }',
        # for-init object whose dtor must run from loop-exit paths
        'for (ProbeSub t; probe_cond(); ) { probe_throw(); }',
        # catch resuming inside a ctor with members
        'try { probe_throw(); } catch (...) { ProbeSub t; probe_throw(); }',
        # object init from throwing call in member-init list
        '{ ProbeSub t = *probe_psub(); probe_throw(); }',
        # nested conditional scopes
        'if (probe_cond()) { if (probe_cond()) { ProbeSub t; '
        'probe_throw(); } }',
        # temp bound to ref across try boundary
        '{ ProbeSub const &t = *probe_psub(); probe_throw(); }',
        # do-while scoped object
        'do { ProbeSub t; probe_throw(); } while (0);',
        # comma-separated construction
        '{ ProbeSub t; probe_cond(), probe_throw(); }',
        # conditional-expression temporaries: MSVC tracks which arm's temp
        # exists with a flag bit -> and eax,bit; jz; and [flag],~bit
        '{ ProbeDtor t = probe_cond() ? probe_make() : probe_make(); '
        'probe_throw(); }',
        '{ ProbeD4 t = probe_cond() ? probe_make4() : probe_make4(); '
        'probe_throw(); }',
        '{ ProbeDtor &&t = probe_cond() ? probe_make() : probe_make(); '
        'probe_sink(&t); probe_throw(); }',
        '{ ProbeD4 &&t = probe_cond() ? probe_make4() : probe_make4(); '
        'probe_sink(&t); probe_throw(); }',
        '{ (probe_cond() ? probe_make() : probe_make()); probe_throw(); }',
        '{ ProbeDtor const &t = probe_cond() ? probe_make() : probe_make(); '
        'probe_throw(); }',
        '{ ProbeD4 const &t = probe_cond() ? probe_make4() : probe_make4(); '
        'probe_throw(); }',
        # two independent conditional locals -> two flag bits
        '{ ProbeSub a; if (probe_cond()) { a.~ProbeSub(); } '
        'probe_throw(); }',
        # && / || with constructed operand
        'if (probe_cond() && (probe_make(), true)) { probe_throw(); }',
        # argument temporaries: evaluated right-to-left, so partial
        # construction cannot be a single EH state -> bit flags
        'probe_sink2(probe_make(), probe_make());',
        'probe_sink24(probe_make4(), probe_make4());',
        'probe_sinkm(probe_make(), probe_make4(), probe_make());',
        'probe_sink2(probe_cond() ? probe_make() : *probe_pdt(), '
        'probe_make());',
        'probe_sink24(probe_make4(), '
        'probe_cond() ? probe_make4() : probe_make4());',
        '{ probe_sink2(probe_make(), probe_make()); probe_throw(); }',
        '{ probe_sink24(probe_make4(), probe_make4()); probe_throw(); }',
        # ?: arms from different sources -> flag picks which temp exists
        '{ ProbeDtor t = probe_cond() ? *probe_pdt() : probe_make(); '
        'probe_throw(); }',
        '{ ProbeDtor t = probe_cond() ? probe_make() : *probe_pdt(); '
        'probe_throw(); }',
    )
    for vi, v in enumerate(variants):
        for d in range(6):
            out.append(
                f'void probe_flag_{vi}_{d}() {{ '
                + _nest(v, d)
                + ' }'
            )
    # SEH __try/__except filters receive the establisher frame through a
    # second stack arg -> mov edx,[esp+8]; lea eax,[edx+0xc]; xor-checked
    # field loads + calls. Sweeping locals shifts the field offsets.
    for d in range(count):
        out.append(
            f'void probe_seh_{d}() {{ '
            + _nest('__try { probe_throw(); } '
                    '__except(probe_cond()) { probe_sink(0); }', d,
                    decl='ProbePOD')
            + ' }'
        )
        out.append(
            f'void probe_sehf_{d}() {{ '
            + _nest('__try { probe_throw(); } '
                    '__finally { probe_sink(0); }', d,
                    decl='ProbePOD')
            + ' }'
        )


def emit_universal_trivia(out):
    """Emit the common leaf bodies unconditionally.

    Ghidra-missed functions have no inventory row, so trivial_entries never
    emits them; the windowed matcher only needs an object containing the
    bytes. One copy of each shape is enough -- matches are per-VA.
    """
    out.append('int probe_tv_zero() { return 0; }')
    out.append('int probe_tv_one() { return 1; }')
    out.append('bool probe_tv_true() { return true; }')
    out.append('bool probe_tv_false() { return false; }')
    out.append('void *probe_tv_arg(void *a0) { return a0; }')
    out.append('void *__stdcall probe_tv_sarg(void *a0) { return a0; }')
    out.append('void *__stdcall probe_tv_sarg2(void *a0, void *a1) '
               '{ return a0; }')
    out.append('void *__stdcall probe_tv_sarg3(void *a0, void *a1, void *a2) '
               '{ return a0; }')
    out.append('void *__stdcall probe_tv_sarg4(void *a0, void *a1, void *a2,'
               ' void *a3) { return a0; }')
    # member getters/setters at the offsets the reference uses most
    for off in (0, 4, 8, 0xc, 0x10, 0x14, 0x18, 0x1c, 0x20, 0x24, 0x28,
                0x2c, 0x30, 0x34, 0x38, 0x3c, 0x40, 0x44, 0x48, 0x4c):
        pad = f'char p[{off}]; ' if off else ''
        out.append(
            f'struct ProbeTV{off:02x} {{ {pad}int m; int g_{off:02x}(); }};\n'
            f'int ProbeTV{off:02x}::g_{off:02x}() {{ return m; }}'
        )
        out.append(
            f'struct ProbeTL{off:02x} {{ {pad}int m; int *a_{off:02x}(); }};\n'
            f'int *ProbeTL{off:02x}::a_{off:02x}() {{ return &m; }}'
        )
    # indexed helpers:  mov eax,[esp+8]; lea ecx,[eax*N]; ...
    for k in range(1, 6):
        out.append(
            f'int *probe_idx{k}(int *a, int i) {{ return a + i * {k}; }}'
        )


def trivial_entries(reference, image, layout, inventory):
    """Uncovered inventory entries that are trivially reproducible bodies.

    Each recognized byte shape maps to a C++ snippet that MSVC compiles to
    exactly those bytes under /O2. Member-form bodies are emitted as a
    method named FUN_<va> on a per-address stub struct so the mangled
    symbol still binds to the index name.
    """
    import re as _re
    base = layout['image_base']
    text = next(s for s in layout['sections'] if s['name'] == '.text')
    o, rs, rva0 = text['raw_offset'], text['raw_size'], text['rva']
    rows = []

    for row in csv.DictReader(open(inventory), delimiter='\t'):
        va = int(row['entry'], 16)
        size = int(row['body_bytes'])
        if not size or size > 24:
            continue
        rva = va - base
        if not (rva0 <= rva < rva0 + rs):
            continue
        off = o + rva - rva0
        exp = reference[off:off + size]
        if image[off:off + size] == exp:
            continue
        n = f'FUN_{va:08x}'
        body = None
        # return constant:  b8 imm32 c3  |  b0 01/00 c3  |  33 c0 c3
        m = _re.fullmatch(rb'\xb8(....)\xc3', exp)
        if m:
            body = f'int {n}() {{ return {int.from_bytes(m.group(1), "little")}; }}'
        elif exp == b'\xb0\x01\xc3':
            body = f'bool {n}() {{ return true; }}'
        elif exp == b'\x33\xc0\xc3':
            body = f'int {n}() {{ return 0; }}'
        # return arg0:  8b 44 24 04 (c2 imm16 stdcall | c3 cdecl)
        m = _re.fullmatch(rb'\x8b\x44\x24\x04(\xc2(..)|\xc3)', exp)
        if m and not body:
            if m.group(1) != b'\xc3':
                nargs = int.from_bytes(m.group(2), 'little') // 4
                args = ', '.join(f'void *a{i}' for i in range(nargs))
                body = f'void *__stdcall {n}({args}) {{ return a0; }}'
            else:
                body = f'void *{n}(void *a0) {{ return a0; }}'
        # member getter:  8b 41 NN c3 int | 66 8b 41 NN c3 short |
        #                 8b 81 NNNN c3 disp32 | 8d 41 NN c3 address
        m = _re.fullmatch(rb'\x8b\x41(.)\xc3', exp)
        if m and not body:
            off8 = m.group(1)[0]
            body = (f'struct GS{va:08x} {{ char p[{off8}]; int m; '
                    f'int {n}(); }};\n'
                    f'int GS{va:08x}::{n}() {{ return m; }}')
        m = _re.fullmatch(rb'\x66\x8b\x41(.)\xc3', exp)
        if m and not body:
            off8 = m.group(1)[0]
            body = (f'struct GS{va:08x} {{ char p[{off8}]; short m; '
                    f'short {n}(); }};\n'
                    f'short GS{va:08x}::{n}() {{ return m; }}')
        m = _re.fullmatch(rb'\x8b\x81(....)\xc3', exp)
        if m and not body:
            off32 = int.from_bytes(m.group(1), 'little')
            body = (f'struct GS{va:08x} {{ char p[{off32}]; int m; '
                    f'int {n}(); }};\n'
                    f'int GS{va:08x}::{n}() {{ return m; }}')
        m = _re.fullmatch(rb'\x8d\x41(.)\xc3', exp)
        if m and not body:
            off8 = m.group(1)[0]
            body = (f'struct GS{va:08x} {{ char p[{off8}]; int m; '
                    f'int *{n}(); }};\n'
                    f'int *GS{va:08x}::{n}() {{ return &m; }}')
        # setter:  8b 44 24 04 c7 00 imm32 c2 imm16
        m = _re.fullmatch(rb'\x8b\x44\x24\x04\xc7\x00(....)\xc2(..)', exp)
        if m and not body:
            v = int.from_bytes(m.group(1), 'little')
            nargs = int.from_bytes(m.group(2), 'little') // 4
            rest = ', '.join(f'void *a{i}' for i in range(1, nargs))
            sig = 'int *p' + (', ' + rest if rest else '')
            body = f'void __stdcall {n}({sig}) {{ *p = {v}; }}'
        # bool arg writer: 8b442404 c6 00 01 b0 01 c2 imm16
        m = _re.fullmatch(rb'\x8b\x44\x24\x04\xc6\x00\x01\xb0\x01\xc2(..)', exp)
        if m and not body:
            nargs = int.from_bytes(m.group(1), 'little') // 4
            rest = ', '.join(f'void *a{i}' for i in range(1, nargs))
            sig = 'char *p' + (', ' + rest if rest else '')
            body = f'bool __stdcall {n}({sig}) {{ *p = 1; return true; }}'
        if body:
            rows.append((va, body))
        elif size == 6 and exp[:2] == b'\xff\x25':
            rows.append((va, 'IAT'))
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--sweep', type=int, default=70)
    ap.add_argument('--out', type=Path, required=True)
    ap.add_argument('--reference', type=Path)
    ap.add_argument('--image', type=Path)
    ap.add_argument('--report', type=Path)
    ap.add_argument('--inventory', type=Path,
                    default='analysis/thunk-recovery-full/final-function-inventory.tsv')
    ap.add_argument('--index-out', type=Path)
    args = ap.parse_args()

    out = [HEADER]
    emit_lea_chains(out, args.sweep)
    emit_mov_chains(out, args.sweep)
    emit_member_sweep(out, args.sweep)
    emit_flag_members(out, 16)
    emit_throwing_flags(out, 16)
    emit_member_new_probes(out, args.sweep)
    emit_array_members(out, min(args.sweep, 40))
    emit_delete_chains(out, args.sweep)
    emit_array_sweep(out, args.sweep)
    emit_extra_families(out, 12)
    emit_universal_trivia(out)

    index_rows = []
    if args.reference and args.image and args.report:
        reference = args.reference.read_bytes()
        image = args.image.read_bytes()
        layout = json.loads(args.report.read_text())['layout']
        emit_targeted(out, needed_operands(reference, image, layout,
                                           args.inventory))
        sizes = {}
        for row in csv.DictReader(open(args.inventory), delimiter='\t'):
            va = int(row['entry'], 16)
            if row['body_bytes']:
                sizes[va] = int(row['body_bytes'])
        for va, body in trivial_entries(reference, image, layout,
                                        args.inventory):
            if body == 'IAT':
                out.append(
                    f"extern __declspec(dllimport) void probe_import_{va:08x}();\n"
                    f"void FUN_{va:08x}() {{ probe_import_{va:08x}(); }}"
                )
            else:
                out.append(body)
            index_rows.append((f'{va:08x}', f'FUN_{va:08x}', str(sizes[va])))

    args.out.write_text('\n'.join(out) + '\n')
    if args.index_out:
        args.index_out.parent.mkdir(parents=True, exist_ok=True)
        args.index_out.write_text(
            'entry\tname\treference_body_bytes\n'
            + '\n'.join('\t'.join(r) for r in index_rows) + '\n')
    print(f'wrote {args.out}: {len(out)} lines, {len(index_rows)} index rows')


if __name__ == '__main__':
    main()
