#!/usr/bin/env python3
"""Generate a synthetic EH-funclet calibration corpus (real C++, no assembly).

The reference DLL's unwind funclets are self-contained code such as
``lea ecx,[ebp-off]; jmp ~T`` that depend only on the parent's frame layout,
not on the parent's identity. A probe function with a destructable local at a
chosen stack offset emits the same funclet. This generator sweeps padding so
the produced funclets cover every disp8 operand the reference uses.
"""
import argparse,csv,json
from pathlib import Path

HEADER = """// Generated by tools/make_eh_probe_corpus.py -- real C++ funclet probes.
struct ProbeDtor { ProbeDtor(); ~ProbeDtor(); };
struct ProbeSub { ~ProbeSub(); };
struct ProbeHost { ProbeSub m; ProbeHost(); };
extern void probe_throw();
extern void probe_sink(void *);
extern ProbeDtor probe_make();
ProbeHost::ProbeHost() { probe_throw(); }
"""


def emit_lea_sweep(out, count):
    # Unwind action for a plain local: lea ecx,[ebp-off]; jmp ~ProbeDtor
    for k in range(count):
        out.append(
            f"void probe_lea_{k:04d}() {{ int pad[{k + 1}]; probe_sink(&pad[0]); "
            f"ProbeDtor t; probe_throw(); }}"
        )


def emit_mov_sweep(out, count):
    # Copy-initialised temporary: hidden pointer slot -> mov ecx,[ebp-off]; jmp
    for k in range(count):
        out.append(
            f"void probe_mov_{k:04d}() {{ int pad[{k + 1}]; probe_sink(&pad[0]); "
            f"ProbeDtor t = probe_make(); probe_throw(); }}"
        )


def emit_member_sweep(out, count):
    # Member cleanup in a ctor unwinds via this=[ebp+8]:
    #   member at offset 0 -> mov ecx,[ebp+8]; jmp ~Sub        (8 bytes)
    #   member at offset N -> mov ecx,[ebp+8]; add ecx,N; jmp  (11 bytes)
    for k in range(count):
        pad = f'int pad[{k}]; ' if k else ''
        out.append(
            f"struct ProbeHost{k:04d} {{ {pad}ProbeSub m; "
            f"ProbeHost{k:04d}(); }};\n"
            f"ProbeHost{k:04d}::ProbeHost{k:04d}() {{ probe_throw(); }}"
        )


def emit_array_sweep(out, count):
    # Array dtor -> flag/vector cleanup funclets.
    for k in range(count):
        out.append(
            f"void probe_arr_{k:04d}() {{ int pad[{k + 1}]; probe_sink(&pad[0]); "
            f"ProbeDtor a[4]; probe_throw(); }}"
        )


def trivial_entries(reference, image, layout, inventory):
    """Uncovered inventory entries that are trivially reproducible bodies."""
    base = layout['image_base']
    text = next(s for s in layout['sections'] if s['name'] == '.text')
    o, rs, rva0 = text['raw_offset'], text['raw_size'], text['rva']
    b001, iat = [], []
    for row in csv.DictReader(open(inventory), delimiter='\t'):
        va = int(row['entry'], 16)
        size = int(row['body_bytes'])
        if not size:
            continue
        rva = va - base
        if not (rva0 <= rva < rva0 + rs):
            continue
        off = o + rva - rva0
        exp = reference[off:off + size]
        if image[off:off + size] == exp:
            continue
        if exp == b'\xb0\x01\xc3':
            b001.append(va)
        elif size == 6 and exp[:2] == b'\xff\x25':
            iat.append(va)
    return b001, iat


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--sweep', type=int, default=70)
    ap.add_argument('--out', type=Path, required=True)
    ap.add_argument('--reference', type=Path)
    ap.add_argument('--image', type=Path)
    ap.add_argument('--report', type=Path)
    ap.add_argument('--inventory', type=Path,
                    default='analysis/thunk-recovery-full/final-function-inventory.tsv')
    ap.add_argument('--index-out', type=Path)
    args = ap.parse_args()

    out = [HEADER]
    emit_lea_sweep(out, args.sweep)
    emit_mov_sweep(out, args.sweep)
    emit_member_sweep(out, args.sweep)
    emit_array_sweep(out, args.sweep)

    index_rows = []
    if args.reference and args.image and args.report:
        reference = args.reference.read_bytes()
        image = args.image.read_bytes()
        layout = json.loads(args.report.read_text())['layout']
        b001, iat = trivial_entries(reference, image, layout, args.inventory)
        for va in b001:
            out.append(f"bool FUN_{va:08x}() {{ return true; }}")
            index_rows.append((f'{va:08x}', f'FUN_{va:08x}', '3'))
        for va in iat:
            out.append(
                f"extern __declspec(dllimport) void probe_import_{va:08x}();\n"
                f"void FUN_{va:08x}() {{ probe_import_{va:08x}(); }}"
            )
            index_rows.append((f'{va:08x}', f'FUN_{va:08x}', '6'))

    args.out.write_text('\n'.join(out) + '\n')
    if args.index_out:
        args.index_out.parent.mkdir(parents=True, exist_ok=True)
        args.index_out.write_text(
            'entry\tname\treference_body_bytes\n'
            + '\n'.join('\t'.join(r) for r in index_rows) + '\n')
    print(f'wrote {args.out}: {len(out)} lines, {len(index_rows)} index rows')


if __name__ == '__main__':
    main()
